### ISSUE TITLE
Could not start application ibrowse: could not find application file: ibrowse.app

### ISSUE THREAD

**Issue by zweizeichen** [wistia/elixir_nsq#2]
Hey,
thank you for writing this package! I encountered some problems when downloading the package in the way suggested in the readme (`{:elixir_nsq, "~> 1.0.3"}`). If I choose to pull directly from git (`{:elixir_nsq, github: "wistia/elixir_nsq"}`), everything works fine. It seems to be related to ibrowse not being pulled correctly from git when the release version was fetched from hex.

Steps to reproduce:
1. `mix new test`
2. `test/mix.exs`
   
   ``` elixir
   defmodule Test.Mixfile do
   use Mix.Project
   
   def project do
     [app: :test,
      version: "0.0.1",
      elixir: "~> 1.2",
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      deps: deps]
   end
   
   # Configuration for the OTP application
   #
   # Type "mix help compile.app" for more information
   def application do
     [applications: [:logger, :elixir_nsq]]
   end
   
   # Dependencies can be Hex packages:
   #
   #   {:mydep, "~> 0.3.0"}
   #
   # Or git/path repositories:
   #
   #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
   #
   # Type "mix help deps" for more examples and options
   defp deps do
     [{:elixir_nsq, "~> 1.0.3"}]
   end
   end
   ```
3. `mix deps.get; mix deps.compile --all`
4. `mix run --no-halt`

> =INFO REPORT==== 17-Jun-2016::16:09:40 ===
>     application: logger
>     exited: stopped
>     type: temporary
> *\* (Mix) Could not start application ibrowse: could not find application file: ibrowse.app

**Comment by MaxPower15** [comment]
Thanks for the report! I've been thinking that I should switch it to using httpoison since that seems to be the more commonly depended-on library.

Until I get a fix up for this, your work-around of referencing github directly seems good.

**Comment by MaxPower15** [comment]
Instead of switching to HTTPoison, I switched our dep to the hex package of ibrowse, which is the same thing that newer versions of HTTPotion do. https://github.com/wistia/elixir_nsq/commit/bb3d839aa5228cbb1f5e63ae6f3978da1e4746e9

The problem was that our target package was relying on the version _just_ before they stopped requiring `:ibrowse` from github to appear in the deps along with `:httpotion`: https://github.com/myfreeweb/httpotion/tree/v2.1.0.

Anyway, I believe this fixes the issue. If not, please reopen!

**Comment by MaxPower15** [comment]
Actually gonna keep this open for reference until I push up a new version of the hex package.
