### ISSUE TITLE
Elixir.ArithmeticError

### ISSUE THREAD

**Issue by kswin** [wistia/elixir_nsq#28]
This error occurred after our application failed to write some db records. While the initial issue is app-based, we think it uncovered a bug in this area. 

Elixir.ArithmeticError bad argument in arithmetic expression 
    lib/nsq/consumer/backoff.ex:175 NSQ.Consumer.Backoff.exponential_backoff/1
    lib/nsq/consumer/backoff.ex:83 NSQ.Consumer.Backoff.backoff/3
    lib/nsq/consumer/backoff.ex:29 NSQ.Consumer.Backoff.start_stop_continue/3
    lib/nsq/consumer/backoff.ex:36 NSQ.Consumer.Backoff.start_stop_continue!/3
    lib/nsq/consumer.ex:221 NSQ.Consumer.handle_call/3
    gen_server.erl:661 :gen_server.try_handle_call/4
    gen_server.erl:690 :gen_server.handle_msg/6
    proc_lib.erl:249 :proc_lib.init_p_do_apply/3

**Comment by blatyo** [comment]
Also, we're not specifying any config except `message_handler`, `nsqds`, and `nsqlookupds`. So we should be getting the defaults for backoff.
